# Generated by Django 6.0.6 on 2026-06-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('HARDWARE', 'Hardware Repair (Phone/Laptop/Gaming)'), ('SOFTWARE', 'Software Service (OS/App Installation)'), ('DIGITAL', 'Digital Delivery (Licenses/Data Recovery)')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_hours', models.PositiveIntegerField(help_text='Estimated hours to complete')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MKUMBWA_TRONIX.category')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WALK_IN', 'Walk-in (Direct Office Visit)'), ('REMOTE', 'Remote (Online Service Only)'), ('ONLINE_TO_PHYSICAL', 'Online Booking → Office Visit')], default='WALK_IN', max_length=20)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('device_type', models.CharField(help_text='e.g., Phone, Laptop, PS5, PC', max_length=100)),
                ('device_model', models.CharField(help_text='e.g., iPhone 13, Dell XPS 13, PS5 Slim', max_length=150)),
                ('serial_or_imei', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_notes', models.TextField(help_text='Customer description of the fault or requirement')),
                ('tech_diagnostic_notes', models.TextField(blank=True, help_text='Internal notes by the technician', null=True)),
                ('quoted_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted to customer after assessment', max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final charge after job completion', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('PROCESSING', 'In Progress / Repairing'), ('AWAITING_PARTS', 'Awaiting Spare Parts'), ('TESTING', 'Quality Control Testing'), ('READY', 'Ready for Pickup / Delivery'), ('COMPLETED', 'Completed & Closed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Staff member who created this ticket (for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECHNICIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MKUMBWA_TRONIX.servicetype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliveryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key_or_text', models.TextField(blank=True, help_text='Digital licenses, activation strings, or access codes', null=True)),
                ('secure_delivery_file', models.FileField(blank=True, help_text='Recovered data files, reports, or installers', null=True, upload_to='digital_deliveries/')),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_delivery', to='MKUMBWA_TRONIX.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('CASH', 'Cash'), ('PAYPAL', 'PayPal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, help_text='M-Pesa transaction ID or PayPal reference', max_length=200, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='MKUMBWA_TRONIX.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('PROCESSING', 'In Progress / Repairing'), ('AWAITING_PARTS', 'Awaiting Spare Parts'), ('TESTING', 'Quality Control Testing'), ('READY', 'Ready for Pickup / Delivery'), ('COMPLETED', 'Completed & Closed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('internal_note', models.TextField(blank=True, help_text='Why was the status changed?', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='MKUMBWA_TRONIX.servicerequest')),
            ],
            options={
                'verbose_name_plural': 'Service Status Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('HARDWARE', 'Hardware Repair'), ('SOFTWARE', 'Software Services'), ('BOTH', 'Hardware & Software')], max_length=20)),
                ('bio', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
