# Generated by Django 6.0.6 on 2026-06-29 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0003_gallerypost_workupdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='specialization',
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='employee_id',
            field=models.CharField(default='MT-TECH-000', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_active_bench',
            field=models.BooleanField(default=True, help_text='Designates whether this technician can log into the bench workspace.'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='specialty',
            field=models.CharField(blank=True, help_text='e.g., Micro-soldering, Logic Boards, Firmware', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
