# Generated by Django 6.0.6 on 2026-07-04 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0004_remove_technicianprofile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='specialization',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Repair'), ('SOFTWARE', 'Software Services'), ('BOTH', 'Hardware & Software')], default='BOTH', max_length=20),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_active_bench',
            field=models.BooleanField(default=True, help_text='Can log into technician workspace'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='specialty',
            field=models.CharField(blank=True, help_text='Example: Logic Boards, Micro-soldering', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
