# Generated by Django 6.0.6 on 2026-07-13 08:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0005_technicianprofile_bio_technicianprofile_is_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('sku', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SCREEN', 'Screens & Displays'), ('BATTERY', 'Batteries'), ('CHIP', 'Microchips & ICs'), ('PORT', 'Charging & HDMI Ports'), ('OTHER', 'Other Component Hardware')], max_length=20)),
                ('quantity_on_hand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stock_limit', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartsConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField(default=1)),
                ('date_consumed', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='MKUMBWA_TRONIX.inventoryitem')),
                ('repair_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='MKUMBWA_TRONIX.servicerequest')),
            ],
        ),
    ]
