# Generated by Django 6.0.6 on 2026-07-22 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0007_rename_repair_request_partsconsumption_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_request',
            field=models.ForeignKey(blank=True, help_text="The job this notification is about, if any (used to sync 'claimed' state across all technicians)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='MKUMBWA_TRONIX.servicerequest'),
        ),
    ]
