# Generated by Django 6.0.6 on 2026-07-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0009_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('USED', 'Used / Extracted'), ('REFURB', 'Refurbished')], default='NEW', max_length=10),
        ),
    ]
