# Generated by Django 6.0.6 on 2026-07-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0010_accessory_buy_price_inventoryitem_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MKUMBWA_TRONIX.servicetype'),
        ),
    ]
