# Generated by Django 6.0.6 on 2026-07-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0011_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='usable_as_spare',
            field=models.BooleanField(default=False, help_text='If true, this item is also mirrored into the Spares Vault for use on repair jobs'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('SCREEN', 'Screens & Displays'), ('BATTERY', 'Batteries'), ('CHIP', 'Microchips & ICs'), ('PORT', 'Charging & HDMI Ports'), ('ACCESSORY', 'Mirrored from Accessories'), ('OTHER', 'Other Component Hardware')], max_length=20),
        ),
    ]
