# Generated by Django 6.0.6 on 2026-07-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MKUMBWA_TRONIX', '0012_accessory_usable_as_spare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='sku',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='quantity_brought',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='quantity_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
